# GitHub Action for Bug Tracker

name: BUG TRACKER

on: 
  pull_request:
    branches: [ main ]

jobs:
  bug-tracker:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          php-version: 8.1.31

      - name: Run Tests
        run: |
          php artisan test



        
