# GitHub Action for Bug Tracker

name: BUG TRACKER

on: 
  pull_request:
    branches:
      - main

jobs:
  bug-tracker:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Tests
        run: |
          php artisan test

      - name: Run PHPStan
        run: |
          php vendor/bin/phpstan analyse



        
